apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: Repository
metadata:
  name: deno-kcp
  namespace: default
spec:
  branch: spec/bidder-and-bob-pds
  populate:
    partition: directory
    summarize: true
  source: {}
  verify:
  - go
  - test
  - ./...
status:
  headCommit: 44bd6951fa6bf8f6e6d0264e27b7dfe6b967e21e
  indexedCommit: 44bd6951fa6bf8f6e6d0264e27b7dfe6b967e21e
  phase: Indexing
