apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: internal-provider-s2c-993d65b47662
  namespace: default
spec:
  systemContext: internal-provider
  direction: SpecToCode
  fromSpecHash: 9bc86161d5382c9a2625b793b5bf7b3b7ed45887cba37d67c7c79171c5944a0d
  toSpecHash: 993d65b476623832febe51723908f4daa3a597748d75416bd5a62b6d2dd4ae46
  delta:
    counts:
      added: 2
    requirements:
    - +r.watch-cache-keys-every-workspace
    - +r.watch-cache-keys-every-workspace-test
status:
  phase: Pending
