apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: internal-policyworkflowrun-c2s-25d10f922ec7-25d10f922ec7
  namespace: default
spec:
  delta: {}
  direction: CodeToSpec
  fromCommit: 25d10f922ec7360cc7247da945a6fe49e88cf7ab
  systemContext: internal-policyworkflowrun
  toCommit: 25d10f922ec7360cc7247da945a6fe49e88cf7ab
status:
  message: the agent is summarizing internal-policyworkflowrun
  phase: Running
