#!/usr/bin/env python3
"""Write VIOLATIONS.md, the catalogue of every violation every policy can raise.

Reads `data.deno_kcp.metadata`, which is the union of every policy's own
metadata object, and renders it grouped by policy and ordered by severity.

    python3 opa/tools/catalogue.py [--opa opa] [--out opa/VIOLATIONS.md]
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OPA_ROOT = os.path.dirname(HERE)

SEVERITY_ORDER = {"error": 0, "warning": 1, "info": 2}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--opa", default=os.environ.get("OPA", "opa"))
    parser.add_argument("--out", default=os.path.join(OPA_ROOT, "VIOLATIONS.md"))
    args = parser.parse_args()

    proc = subprocess.run(
        [args.opa, "eval", "-b", OPA_ROOT, "--format", "json", "data.deno_kcp.metadata"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr[:4000])
        return 1
    metadata = json.loads(proc.stdout)["result"][0]["expressions"][0]["value"]

    total = sum(len(v) for v in metadata.values())
    lines = [
        "# Violations",
        "",
        f"Every violation the policies in this tree can raise: {total} across "
        f"{len(metadata)} policy sets.",
        "",
        "Generated by `python3 opa/tools/catalogue.py`. The id a report keys a "
        "finding off is `<policy>/<violation>`. Every rule has a unit test that "
        "makes it fire; many never fire on the two real documents, because "
        "neither carries the shape they guard against.",
        "",
    ]

    for policy in sorted(metadata):
        rules = metadata[policy]
        errors = sum(1 for m in rules.values() if m.get("severity") == "error")
        warnings = sum(1 for m in rules.values() if m.get("severity") == "warning")
        infos = sum(1 for m in rules.values() if m.get("severity") == "info")
        lines.append(f"## `{policy}`")
        lines.append("")
        lines.append(
            f"{len(rules)} violations: {errors} error, {warnings} warning, {infos} info."
        )
        lines.append("")
        lines.append("| violation | severity | level | what it catches |")
        lines.append("| --- | --- | --- | --- |")
        rows = sorted(
            rules.items(),
            key=lambda kv: (SEVERITY_ORDER.get(kv[1].get("severity"), 9), kv[0]),
        )
        for violation, meta in rows:
            lines.append(
                f"| `{policy}/{violation}` | {meta.get('severity', '')} "
                f"| {meta.get('level', '')} | {meta.get('title', '')} |"
            )
        lines.append("")

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
        handle.write("\n")
    print(f"catalogue: {total} violations across {len(metadata)} policy sets -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
