apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1alpha1-4.denojobs.deno.computer
spec:
  group: deno.computer
  names:
    kind: DenoJob
    listKind: DenoJobList
    plural: denojobs
    singular: denojob
    shortNames:
      - djob
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              template:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              completions:
                type: integer
                format: int32
              parallelism:
                type: integer
                format: int32
              backoffLimit:
                type: integer
                format: int32
              suspend:
                type: boolean
              activeDeadlineSeconds:
                type: integer
                format: int64
              ttlSecondsAfterFinished:
                type: integer
                format: int64
            required:
              - template
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                  - Pending
                  - Running
                  - Succeeded
                  - Failed
              runName:
                type: string
              runs:
                type: array
                items:
                  type: string
              startTime:
                type: string
                format: date-time
              completionTime:
                type: string
                format: date-time
              active:
                type: integer
                format: int32
              ready:
                type: integer
                format: int32
              succeeded:
                type: integer
                format: int32
              failed:
                type: integer
                format: int32
              retries:
                type: integer
                format: int32
              exitCode:
                type: integer
                format: int32
              outputs:
                type: object
                additionalProperties:
                  type: string
              conditions:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
