package deno_kcp.policies.code_safety

import rego.v1

import data.deno_kcp.lib.violation

# code_safety decides whether a code diff realizes a spec change without
# breaking the project's non-negotiables, stated in CLAUDE.md section "RFP flow
# is the spine" and "ANTI-PATTERNS". It reads input.diff, a unified diff keyed
# by file, and it analyses the lines the change ADDS, because the question is
# what the change brings in, not what it leaves behind.
#
# Three families of rule:
#   provisioning-*  a guest comes up from the RFP flow's cloud-init user_data,
#                   through runComputeContract; nothing provisions one by hand.
#   ts-*            the TypeScript ABC layering: no env reads or hardcoded
#                   ports in a CLI, no raw Deno.serve, no I/O in lib/abc, no
#                   common importing project-local code, no cycles, no
#                   sub-module exports, no comments in code.
#   safety-*        the class of defect this repository's real change contains:
#                   an http:// fetch of a TLS listener, a disabled verification,
#                   a secret committed in source.
#
# Every rule under violations/ contributes to `violations`. The metadata below
# names the severity, the level and a title for each id, once, so a rule states
# only what it found.

policy_id := "code_safety"

# The diff under review. It is null on a run that reviews only a spec tree, so
# every rule goes through lib/code, which tolerates it.
diff := object.get(input, "diff", null)

# The system context of the change under review, used to label a code finding.
review_context := context if {
	change := object.get(input, "change", null)
	is_object(change)
	spec := object.get(change, "spec", {})
	is_object(spec)
	context := object.get(spec, "systemContext", "")
}

review_context := "" if {
	not is_object(object.get(input, "change", null))
}

# code_location labels a finding in a file on disk with its path and line.
code_location(file, line) := violation.file_location(review_context, file, line)

# finding builds a violation for one added line. details.line carries the
# offending text, as every code rule must quote the line it found.
finding(id, row, message, details) := v if {
	v := violation.build(
		policy_id,
		id,
		code_location(row.path, row.line),
		message,
		object.union({"file": row.path, "line": row.text, "line_number": row.line}, details),
	)
}

# metadata names, for every violation this policy can raise, the severity it
# carries, the requirement level it corresponds to, and a one-line title. The
# aggregator joins it into each violation by id.
metadata := {
	"provisioning-container-run": {"severity": "error", "level": "MUST", "title": "A container is started by hand instead of through the RFP flow"},
	"provisioning-container-exec": {"severity": "error", "level": "MUST", "title": "A command is run inside a container by hand"},
	"provisioning-apt-install-in-container": {"severity": "error", "level": "MUST", "title": "A package is installed into a container by hand"},
	"provisioning-manual-authorized-keys": {"severity": "error", "level": "MUST", "title": "authorized_keys is written by hand"},
	"provisioning-ssh-keygen": {"severity": "error", "level": "MUST", "title": "An ssh keypair is generated by hand"},
	"provisioning-mount-binary": {"severity": "error", "level": "MUST", "title": "A host binary is mounted into a guest"},
	"provisioning-cross-compiled-agent": {"severity": "error", "level": "MUST", "title": "A cross-compiled agent is mounted or copied into a guest"},
	"provisioning-cloud-init-bypass": {"severity": "error", "level": "MUST", "title": "The cloud-init user_data path is skipped"},
	"provisioning-direct-guest-access": {"severity": "error", "level": "MUST", "title": "A guest is reached without the relay"},
	"provisioning-new-guest-transport": {"severity": "error", "level": "MUST", "title": "A guest transport is added outside cloud-init-common"},
	"provisioning-test-stands-up-own-container": {"severity": "error", "level": "MUST", "title": "A test stands up its own container instead of driving runComputeContract"},
	"provisioning-second-ssh-transport": {"severity": "error", "level": "MUST", "title": "A second SSH transport the cloud-init does not deploy"},
	"provisioning-hand-written-user-data": {"severity": "error", "level": "MUST", "title": "cloud-config is written by hand rather than through buildUserData"},
	"ts-deno-env-get-in-cli": {"severity": "error", "level": "MUST", "title": "Deno.env.get appears in a CLI"},
	"ts-raw-deno-serve": {"severity": "error", "level": "MUST", "title": "Deno.serve is called outside createServe"},
	"ts-hardcoded-port": {"severity": "error", "level": "MUST", "title": "A port is hardcoded in code rather than declared in JSON"},
	"ts-subclassed-hono-factory": {"severity": "error", "level": "MUST", "title": "A Hono factory is subclassed rather than composed"},
	"ts-io-in-abc": {"severity": "error", "level": "MUST", "title": "I/O appears in the lib/abc layer"},
	"ts-common-imports-project-local": {"severity": "error", "level": "MUST", "title": "lib/common imports project-local code"},
	"ts-submodule-export": {"severity": "error", "level": "MUST", "title": "A package exports a sub-module instead of one mod.ts"},
	"ts-cross-concept-import": {"severity": "error", "level": "MUST", "title": "One concept's implementation imports another's"},
	"ts-port-sniffing-toctou": {"severity": "error", "level": "MUST", "title": "A port is sniffed then closed then rebound"},
	"ts-signal-handler-outside-cli": {"severity": "error", "level": "MUST", "title": "A signal handler is installed outside a CLI"},
	"ts-bare-common-package-name": {"severity": "error", "level": "MUST", "title": "A package is named bare common"},
	"ts-new-transport-as-flag": {"severity": "error", "level": "MUST", "title": "A transport is selected by a flag inside an existing implementation"},
	"ts-comments-in-code": {"severity": "warning", "level": "SHOULD", "title": "A comment is added to a TypeScript file"},
	"safety-http-fetch-of-tls-listener": {"severity": "error", "level": "MUST", "title": "An http:// fetch of a listener that serves TLS"},
	"safety-insecure-tls-flag": {"severity": "warning", "level": "SHOULD", "title": "A TLS check disables certificate verification"},
	"safety-stale-tls-guidance": {"severity": "warning", "level": "SHOULD", "title": "Printed guidance tells a reader to fetch http:// a TLS listener"},
	"safety-absolute-machine-path-in-manifest": {"severity": "warning", "level": "SHOULD", "title": "An absolute machine path is written into a manifest"},
	"safety-verification-disabled": {"severity": "error", "level": "MUST", "title": "A verification step is disabled by a flag"},
	"safety-trust-all-ca": {"severity": "error", "level": "MUST", "title": "An added trust setting accepts any certificate"},
	"safety-shell-pipe-to-interpreter": {"severity": "error", "level": "MUST", "title": "A download is piped straight into an interpreter"},
	"safety-unpinned-remote-fetch": {"severity": "error", "level": "MUST", "title": "A remote download carries no checksum or version pin"},
	"safety-secret-literal": {"severity": "error", "level": "MUST", "title": "A key, token or password is committed in source"},
	"safety-private-key-in-diff": {"severity": "error", "level": "MUST", "title": "A private key is added to the diff"},
	"safety-disabled-test": {"severity": "error", "level": "MUST", "title": "A test is skipped instead of fixed"},
	"safety-weakened-assertion": {"severity": "error", "level": "MUST", "title": "An assertion is deleted without a replacement"},
}
