apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: cmd-deno-kcp-provider
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
  dependsOn:
  - sc.deno-kcp
  - sc.internal-provider
codeRefIndex:
- file:cmd/deno-kcp-provider/main.go main.go@cmd/deno-kcp-provider/main.go
