apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: internal-denopod
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
  dependsOn:
  - sc.api-v1alpha1
  - sc.deno-kcp
codeRefIndex:
- file:internal/denopod/denopod.go denopod.go@internal/denopod/denopod.go
- file:internal/denopod/denopod_test.go denopod_test.go@internal/denopod/denopod_test.go
