apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/policy/policytest/acl.go acl.go@third_party/openbao/internal/vault/policy/policytest/acl.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-policy-policytest
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
