apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-acceptance-oidc-config
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/acceptance/oidc-config/clients-assignments-test.js
  clients-assignments-test.js@third_party/openbao/ui/tests/acceptance/oidc-config/clients-assignments-test.js
- file:third_party/openbao/ui/tests/acceptance/oidc-config/clients-keys-test.js clients-keys-test.js@third_party/openbao/ui/tests/acceptance/oidc-config/clients-keys-test.js
- file:third_party/openbao/ui/tests/acceptance/oidc-config/providers-scopes-test.js
  providers-scopes-test.js@third_party/openbao/ui/tests/acceptance/oidc-config/providers-scopes-test.js
