apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/types/vault/models/pki/config/crl.d.ts crl.d.ts@third_party/openbao/ui/types/vault/models/pki/config/crl.d.ts
- file:third_party/openbao/ui/types/vault/models/pki/config/urls.d.ts urls.d.ts@third_party/openbao/ui/types/vault/models/pki/config/urls.d.ts
kind: SystemContext
metadata:
  name: third-party-openbao-ui-types-vault-models-pki-config
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
