apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/pages/secrets/backend/database/connection.js connection.js@third_party/openbao/ui/tests/pages/secrets/backend/database/connection.js
- file:third_party/openbao/ui/tests/pages/secrets/backend/database/role.js role.js@third_party/openbao/ui/tests/pages/secrets/backend/database/role.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-pages-secrets-backend-database
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
