apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-models-auth-config
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
