apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/models/policy/acl.js acl.js@third_party/openbao/ui/app/models/policy/acl.js
- file:third_party/openbao/ui/app/models/policy/egp.js egp.js@third_party/openbao/ui/app/models/policy/egp.js
- file:third_party/openbao/ui/app/models/policy/rgp.js rgp.js@third_party/openbao/ui/app/models/policy/rgp.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-models-policy
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
