apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-integration-components
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/integration/components/alert-inline-test.js alert-inline-test.js@third_party/openbao/ui/tests/integration/components/alert-inline-test.js
- file:third_party/openbao/ui/tests/integration/components/alert-popup-test.js alert-popup-test.js@third_party/openbao/ui/tests/integration/components/alert-popup-test.js
- file:third_party/openbao/ui/tests/integration/components/auth-form-test.js auth-form-test.js@third_party/openbao/ui/tests/integration/components/auth-form-test.js
- file:third_party/openbao/ui/tests/integration/components/auth-jwt-test.js auth-jwt-test.js@third_party/openbao/ui/tests/integration/components/auth-jwt-test.js
- file:third_party/openbao/ui/tests/integration/components/autocomplete-input-test.js
  autocomplete-input-test.js@third_party/openbao/ui/tests/integration/components/autocomplete-input-test.js
- file:third_party/openbao/ui/tests/integration/components/b64-toggle-test.js b64-toggle-test.js@third_party/openbao/ui/tests/integration/components/b64-toggle-test.js
- file:third_party/openbao/ui/tests/integration/components/box-radio-test.js box-radio-test.js@third_party/openbao/ui/tests/integration/components/box-radio-test.js
- file:third_party/openbao/ui/tests/integration/components/calendar-widget-test.js
  calendar-widget-test.js@third_party/openbao/ui/tests/integration/components/calendar-widget-test.js
- file:third_party/openbao/ui/tests/integration/components/checkbox-grid-test.js checkbox-grid-test.js@third_party/openbao/ui/tests/integration/components/checkbox-grid-test.js
- file:third_party/openbao/ui/tests/integration/components/chevron-test.js chevron-test.js@third_party/openbao/ui/tests/integration/components/chevron-test.js
- file:third_party/openbao/ui/tests/integration/components/confirm-action-test.js
  confirm-action-test.js@third_party/openbao/ui/tests/integration/components/confirm-action-test.js
- file:third_party/openbao/ui/tests/integration/components/confirm-test.js confirm-test.js@third_party/openbao/ui/tests/integration/components/confirm-test.js
- file:third_party/openbao/ui/tests/integration/components/confirmation-modal-test.js
  confirmation-modal-test.js@third_party/openbao/ui/tests/integration/components/confirmation-modal-test.js
- file:third_party/openbao/ui/tests/integration/components/database-role-edit-test.js
  database-role-edit-test.js@third_party/openbao/ui/tests/integration/components/database-role-edit-test.js
- file:third_party/openbao/ui/tests/integration/components/database-role-setting-form-test.js
  database-role-setting-form-test.js@third_party/openbao/ui/tests/integration/components/database-role-setting-form-test.js
- file:third_party/openbao/ui/tests/integration/components/date-dropdown-test.js date-dropdown-test.js@third_party/openbao/ui/tests/integration/components/date-dropdown-test.js
- file:third_party/openbao/ui/tests/integration/components/diff-version-selector-test.js
  diff-version-selector-test.js@third_party/openbao/ui/tests/integration/components/diff-version-selector-test.js
- file:third_party/openbao/ui/tests/integration/components/download-button-test.js
  download-button-test.js@third_party/openbao/ui/tests/integration/components/download-button-test.js
- file:third_party/openbao/ui/tests/integration/components/edit-form-test.js edit-form-test.js@third_party/openbao/ui/tests/integration/components/edit-form-test.js
- file:third_party/openbao/ui/tests/integration/components/empty-state-test.js empty-state-test.js@third_party/openbao/ui/tests/integration/components/empty-state-test.js
- file:third_party/openbao/ui/tests/integration/components/features-selection-test.js
  features-selection-test.js@third_party/openbao/ui/tests/integration/components/features-selection-test.js
- file:third_party/openbao/ui/tests/integration/components/form-error-test.js form-error-test.js@third_party/openbao/ui/tests/integration/components/form-error-test.js
- file:third_party/openbao/ui/tests/integration/components/form-field-label-test.js
  form-field-label-test.js@third_party/openbao/ui/tests/integration/components/form-field-label-test.js
- file:third_party/openbao/ui/tests/integration/components/form-field-test.js form-field-test.js@third_party/openbao/ui/tests/integration/components/form-field-test.js
- file:third_party/openbao/ui/tests/integration/components/get-credentials-card-test.js
  get-credentials-card-test.js@third_party/openbao/ui/tests/integration/components/get-credentials-card-test.js
- file:third_party/openbao/ui/tests/integration/components/hover-copy-button-test.js
  hover-copy-button-test.js@third_party/openbao/ui/tests/integration/components/hover-copy-button-test.js
- file:third_party/openbao/ui/tests/integration/components/icon-test.js icon-test.js@third_party/openbao/ui/tests/integration/components/icon-test.js
- file:third_party/openbao/ui/tests/integration/components/info-table-item-array-test.js
  info-table-item-array-test.js@third_party/openbao/ui/tests/integration/components/info-table-item-array-test.js
- file:third_party/openbao/ui/tests/integration/components/info-table-row-test.js
  info-table-row-test.js@third_party/openbao/ui/tests/integration/components/info-table-row-test.js
- file:third_party/openbao/ui/tests/integration/components/info-table-test.js info-table-test.js@third_party/openbao/ui/tests/integration/components/info-table-test.js
- file:third_party/openbao/ui/tests/integration/components/json-editor-test.js json-editor-test.js@third_party/openbao/ui/tests/integration/components/json-editor-test.js
- file:third_party/openbao/ui/tests/integration/components/kv-object-editor-test.js
  kv-object-editor-test.js@third_party/openbao/ui/tests/integration/components/kv-object-editor-test.js
- file:third_party/openbao/ui/tests/integration/components/masked-input-test.js masked-input-test.js@third_party/openbao/ui/tests/integration/components/masked-input-test.js
- file:third_party/openbao/ui/tests/integration/components/mfa-form-test.js mfa-form-test.js@third_party/openbao/ui/tests/integration/components/mfa-form-test.js
- file:third_party/openbao/ui/tests/integration/components/mfa-login-enforcement-form-test.js
  mfa-login-enforcement-form-test.js@third_party/openbao/ui/tests/integration/components/mfa-login-enforcement-form-test.js
- file:third_party/openbao/ui/tests/integration/components/mfa-login-enforcement-header-test.js
  mfa-login-enforcement-header-test.js@third_party/openbao/ui/tests/integration/components/mfa-login-enforcement-header-test.js
- file:third_party/openbao/ui/tests/integration/components/mfa-method-list-item-test.js
  mfa-method-list-item-test.js@third_party/openbao/ui/tests/integration/components/mfa-method-list-item-test.js
- file:third_party/openbao/ui/tests/integration/components/modal-test.js modal-test.js@third_party/openbao/ui/tests/integration/components/modal-test.js
- file:third_party/openbao/ui/tests/integration/components/mount-accessor-select-test.js
  mount-accessor-select-test.js@third_party/openbao/ui/tests/integration/components/mount-accessor-select-test.js
- file:third_party/openbao/ui/tests/integration/components/mount-backend-form-test.js
  mount-backend-form-test.js@third_party/openbao/ui/tests/integration/components/mount-backend-form-test.js
- file:third_party/openbao/ui/tests/integration/components/object-list-input-test.js
  object-list-input-test.js@third_party/openbao/ui/tests/integration/components/object-list-input-test.js
- file:third_party/openbao/ui/tests/integration/components/oidc-consent-block-test.js
  oidc-consent-block-test.js@third_party/openbao/ui/tests/integration/components/oidc-consent-block-test.js
- file:third_party/openbao/ui/tests/integration/components/overview-card-test.js overview-card-test.js@third_party/openbao/ui/tests/integration/components/overview-card-test.js
- file:third_party/openbao/ui/tests/integration/components/pagination-controls-test.js
  pagination-controls-test.js@third_party/openbao/ui/tests/integration/components/pagination-controls-test.js
- file:third_party/openbao/ui/tests/integration/components/pgp-file-test.js pgp-file-test.js@third_party/openbao/ui/tests/integration/components/pgp-file-test.js
- file:third_party/openbao/ui/tests/integration/components/pgp-list-test.js pgp-list-test.js@third_party/openbao/ui/tests/integration/components/pgp-list-test.js
- file:third_party/openbao/ui/tests/integration/components/policy-form-test.js policy-form-test.js@third_party/openbao/ui/tests/integration/components/policy-form-test.js
- file:third_party/openbao/ui/tests/integration/components/radial-progress-test.js
  radial-progress-test.js@third_party/openbao/ui/tests/integration/components/radial-progress-test.js
- file:third_party/openbao/ui/tests/integration/components/radio-button-test.js radio-button-test.js@third_party/openbao/ui/tests/integration/components/radio-button-test.js
- file:third_party/openbao/ui/tests/integration/components/raft-join-test.js raft-join-test.js@third_party/openbao/ui/tests/integration/components/raft-join-test.js
- file:third_party/openbao/ui/tests/integration/components/raft-storage-overview-test.js
  raft-storage-overview-test.js@third_party/openbao/ui/tests/integration/components/raft-storage-overview-test.js
- file:third_party/openbao/ui/tests/integration/components/raft-storage-restore-test.js
  raft-storage-restore-test.js@third_party/openbao/ui/tests/integration/components/raft-storage-restore-test.js
- file:third_party/openbao/ui/tests/integration/components/read-more-test.js read-more-test.js@third_party/openbao/ui/tests/integration/components/read-more-test.js
- file:third_party/openbao/ui/tests/integration/components/readonly-form-field-test.js
  readonly-form-field-test.js@third_party/openbao/ui/tests/integration/components/readonly-form-field-test.js
- file:third_party/openbao/ui/tests/integration/components/regex-validator-test.js
  regex-validator-test.js@third_party/openbao/ui/tests/integration/components/regex-validator-test.js
- file:third_party/openbao/ui/tests/integration/components/search-select-test.js search-select-test.js@third_party/openbao/ui/tests/integration/components/search-select-test.js
- file:third_party/openbao/ui/tests/integration/components/search-select-with-modal-test.js
  search-select-with-modal-test.js@third_party/openbao/ui/tests/integration/components/search-select-with-modal-test.js
- file:third_party/openbao/ui/tests/integration/components/secret-edit-test.js secret-edit-test.js@third_party/openbao/ui/tests/integration/components/secret-edit-test.js
- file:third_party/openbao/ui/tests/integration/components/secret-list-header-test.js
  secret-list-header-test.js@third_party/openbao/ui/tests/integration/components/secret-list-header-test.js
- file:third_party/openbao/ui/tests/integration/components/select-test.js select-test.js@third_party/openbao/ui/tests/integration/components/select-test.js
- file:third_party/openbao/ui/tests/integration/components/selectable-card-test.js
  selectable-card-test.js@third_party/openbao/ui/tests/integration/components/selectable-card-test.js
- file:third_party/openbao/ui/tests/integration/components/shamir-flow-test.js shamir-flow-test.js@third_party/openbao/ui/tests/integration/components/shamir-flow-test.js
- file:third_party/openbao/ui/tests/integration/components/shamir-modal-flow-test.js
  shamir-modal-flow-test.js@third_party/openbao/ui/tests/integration/components/shamir-modal-flow-test.js
- file:third_party/openbao/ui/tests/integration/components/stat-text-test.js stat-text-test.js@third_party/openbao/ui/tests/integration/components/stat-text-test.js
- file:third_party/openbao/ui/tests/integration/components/string-list-test.js string-list-test.js@third_party/openbao/ui/tests/integration/components/string-list-test.js
- file:third_party/openbao/ui/tests/integration/components/text-file-test.js text-file-test.js@third_party/openbao/ui/tests/integration/components/text-file-test.js
- file:third_party/openbao/ui/tests/integration/components/toggle-button-test.js toggle-button-test.js@third_party/openbao/ui/tests/integration/components/toggle-button-test.js
- file:third_party/openbao/ui/tests/integration/components/toggle-test.js toggle-test.js@third_party/openbao/ui/tests/integration/components/toggle-test.js
- file:third_party/openbao/ui/tests/integration/components/token-expire-warning-test.js
  token-expire-warning-test.js@third_party/openbao/ui/tests/integration/components/token-expire-warning-test.js
- file:third_party/openbao/ui/tests/integration/components/tool-tip-test.js tool-tip-test.js@third_party/openbao/ui/tests/integration/components/tool-tip-test.js
- file:third_party/openbao/ui/tests/integration/components/toolbar-actions-test.js
  toolbar-actions-test.js@third_party/openbao/ui/tests/integration/components/toolbar-actions-test.js
- file:third_party/openbao/ui/tests/integration/components/toolbar-filters-test.js
  toolbar-filters-test.js@third_party/openbao/ui/tests/integration/components/toolbar-filters-test.js
- file:third_party/openbao/ui/tests/integration/components/toolbar-link-test.js toolbar-link-test.js@third_party/openbao/ui/tests/integration/components/toolbar-link-test.js
- file:third_party/openbao/ui/tests/integration/components/toolbar-test.js toolbar-test.js@third_party/openbao/ui/tests/integration/components/toolbar-test.js
- file:third_party/openbao/ui/tests/integration/components/transit-edit-test.js transit-edit-test.js@third_party/openbao/ui/tests/integration/components/transit-edit-test.js
- file:third_party/openbao/ui/tests/integration/components/transit-key-actions-test.js
  transit-key-actions-test.js@third_party/openbao/ui/tests/integration/components/transit-key-actions-test.js
- file:third_party/openbao/ui/tests/integration/components/ttl-picker-test.js ttl-picker-test.js@third_party/openbao/ui/tests/integration/components/ttl-picker-test.js
- file:third_party/openbao/ui/tests/integration/components/wrap-ttl-test.js wrap-ttl-test.js@third_party/openbao/ui/tests/integration/components/wrap-ttl-test.js
