apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-unit-machines
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/unit/machines/auth-machine-test.js auth-machine-test.js@third_party/openbao/ui/tests/unit/machines/auth-machine-test.js
- file:third_party/openbao/ui/tests/unit/machines/policies-machine-test.js policies-machine-test.js@third_party/openbao/ui/tests/unit/machines/policies-machine-test.js
- file:third_party/openbao/ui/tests/unit/machines/secrets-machine-test.js secrets-machine-test.js@third_party/openbao/ui/tests/unit/machines/secrets-machine-test.js
- file:third_party/openbao/ui/tests/unit/machines/tools-machine-test.js tools-machine-test.js@third_party/openbao/ui/tests/unit/machines/tools-machine-test.js
- file:third_party/openbao/ui/tests/unit/machines/tutorial-machine-test.js tutorial-machine-test.js@third_party/openbao/ui/tests/unit/machines/tutorial-machine-test.js
