apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/command/agentproxyshared/cache/keymanager/manager.go
  manager.go@third_party/openbao/internal/command/agentproxyshared/cache/keymanager/manager.go
- file:third_party/openbao/internal/command/agentproxyshared/cache/keymanager/passthrough.go
  passthrough.go@third_party/openbao/internal/command/agentproxyshared/cache/keymanager/passthrough.go
- file:third_party/openbao/internal/command/agentproxyshared/cache/keymanager/passthrough_test.go
  passthrough_test.go@third_party/openbao/internal/command/agentproxyshared/cache/keymanager/passthrough_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-command-agentproxyshared-cache-keymanager
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
