apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/kubernetes/addon/helpers/current-mount-path.js current-mount-path.js@third_party/openbao/ui/lib/kubernetes/addon/helpers/current-mount-path.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-kubernetes-addon-helpers
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
