apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/command/agent/approle_end_to_end_test.go approle_end_to_end_test.go@third_party/openbao/internal/command/agent/approle_end_to_end_test.go
- file:third_party/openbao/internal/command/agent/auto_auth_preload_token_end_to_end_test.go
  auto_auth_preload_token_end_to_end_test.go@third_party/openbao/internal/command/agent/auto_auth_preload_token_end_to_end_test.go
- file:third_party/openbao/internal/command/agent/cache_end_to_end_test.go cache_end_to_end_test.go@third_party/openbao/internal/command/agent/cache_end_to_end_test.go
- file:third_party/openbao/internal/command/agent/cert_end_to_end_test.go cert_end_to_end_test.go@third_party/openbao/internal/command/agent/cert_end_to_end_test.go
- file:third_party/openbao/internal/command/agent/doc.go doc.go@third_party/openbao/internal/command/agent/doc.go
- file:third_party/openbao/internal/command/agent/jwt_end_to_end_test.go jwt_end_to_end_test.go@third_party/openbao/internal/command/agent/jwt_end_to_end_test.go
- file:third_party/openbao/internal/command/agent/testing.go testing.go@third_party/openbao/internal/command/agent/testing.go
- file:third_party/openbao/internal/command/agent/token_file_end_to_end_test.go token_file_end_to_end_test.go@third_party/openbao/internal/command/agent/token_file_end_to_end_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-command-agent
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
