apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/helper/configutil/config.go config.go@third_party/openbao/internal/helper/configutil/config.go
- file:third_party/openbao/internal/helper/configutil/config_test.go config_test.go@third_party/openbao/internal/helper/configutil/config_test.go
- file:third_party/openbao/internal/helper/configutil/encrypt_decrypt.go encrypt_decrypt.go@third_party/openbao/internal/helper/configutil/encrypt_decrypt.go
- file:third_party/openbao/internal/helper/configutil/encrypt_decrypt_test.go encrypt_decrypt_test.go@third_party/openbao/internal/helper/configutil/encrypt_decrypt_test.go
- file:third_party/openbao/internal/helper/configutil/http_response_headers.go http_response_headers.go@third_party/openbao/internal/helper/configutil/http_response_headers.go
- file:third_party/openbao/internal/helper/configutil/kms.go kms.go@third_party/openbao/internal/helper/configutil/kms.go
- file:third_party/openbao/internal/helper/configutil/lint.go lint.go@third_party/openbao/internal/helper/configutil/lint.go
- file:third_party/openbao/internal/helper/configutil/listener.go listener.go@third_party/openbao/internal/helper/configutil/listener.go
- file:third_party/openbao/internal/helper/configutil/listener_test.go listener_test.go@third_party/openbao/internal/helper/configutil/listener_test.go
- file:third_party/openbao/internal/helper/configutil/merge.go merge.go@third_party/openbao/internal/helper/configutil/merge.go
- file:third_party/openbao/internal/helper/configutil/telemetry.go telemetry.go@third_party/openbao/internal/helper/configutil/telemetry.go
- file:third_party/openbao/internal/helper/configutil/telemetry_test.go telemetry_test.go@third_party/openbao/internal/helper/configutil/telemetry_test.go
- file:third_party/openbao/internal/helper/configutil/userlockout.go userlockout.go@third_party/openbao/internal/helper/configutil/userlockout.go
- file:third_party/openbao/internal/helper/configutil/userlockout_test.go userlockout_test.go@third_party/openbao/internal/helper/configutil/userlockout_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-helper-configutil
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
