apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/command/agentproxyshared/helpers.go helpers.go@third_party/openbao/internal/command/agentproxyshared/helpers.go
- file:third_party/openbao/internal/command/agentproxyshared/helpers_test.go helpers_test.go@third_party/openbao/internal/command/agentproxyshared/helpers_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-command-agentproxyshared
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
