apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/pages/components/auth-config-form/options.js options.js@third_party/openbao/ui/tests/pages/components/auth-config-form/options.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-pages-components-auth-config-form
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
