apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/routes/application.js application.js@third_party/openbao/ui/app/routes/application.js
- file:third_party/openbao/ui/app/routes/loading.js loading.js@third_party/openbao/ui/app/routes/loading.js
- file:third_party/openbao/ui/app/routes/vault.js vault.js@third_party/openbao/ui/app/routes/vault.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-routes
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
