apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-types-vault
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/types/vault/app-types.ts app-types.ts@third_party/openbao/ui/types/vault/app-types.ts
- file:third_party/openbao/ui/types/vault/index.d.ts index.d.ts@third_party/openbao/ui/types/vault/index.d.ts
