apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/command/token/helper.go helper.go@third_party/openbao/internal/command/token/helper.go
- file:third_party/openbao/internal/command/token/helper_external.go helper_external.go@third_party/openbao/internal/command/token/helper_external.go
- file:third_party/openbao/internal/command/token/helper_external_test.go helper_external_test.go@third_party/openbao/internal/command/token/helper_external_test.go
- file:third_party/openbao/internal/command/token/helper_internal.go helper_internal.go@third_party/openbao/internal/command/token/helper_internal.go
- file:third_party/openbao/internal/command/token/helper_internal_test.go helper_internal_test.go@third_party/openbao/internal/command/token/helper_internal_test.go
- file:third_party/openbao/internal/command/token/helper_testing.go helper_testing.go@third_party/openbao/internal/command/token/helper_testing.go
- file:third_party/openbao/internal/command/token/testing.go testing.go@third_party/openbao/internal/command/token/testing.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-command-token
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
