apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/helper/pluginutil/env.go env.go@third_party/openbao/sdk/helper/pluginutil/env.go
- file:third_party/openbao/sdk/helper/pluginutil/multiplexing.go multiplexing.go@third_party/openbao/sdk/helper/pluginutil/multiplexing.go
- file:third_party/openbao/sdk/helper/pluginutil/multiplexing.pb.go multiplexing.pb.go@third_party/openbao/sdk/helper/pluginutil/multiplexing.pb.go
- file:third_party/openbao/sdk/helper/pluginutil/multiplexing_grpc.pb.go multiplexing_grpc.pb.go@third_party/openbao/sdk/helper/pluginutil/multiplexing_grpc.pb.go
- file:third_party/openbao/sdk/helper/pluginutil/multiplexing_test.go multiplexing_test.go@third_party/openbao/sdk/helper/pluginutil/multiplexing_test.go
- file:third_party/openbao/sdk/helper/pluginutil/run_config.go run_config.go@third_party/openbao/sdk/helper/pluginutil/run_config.go
- file:third_party/openbao/sdk/helper/pluginutil/run_config_test.go run_config_test.go@third_party/openbao/sdk/helper/pluginutil/run_config_test.go
- file:third_party/openbao/sdk/helper/pluginutil/runner.go runner.go@third_party/openbao/sdk/helper/pluginutil/runner.go
- file:third_party/openbao/sdk/helper/pluginutil/tls.go tls.go@third_party/openbao/sdk/helper/pluginutil/tls.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-helper-pluginutil
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
