apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-pages-access
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/pages/access/methods.js methods.js@third_party/openbao/ui/tests/pages/access/methods.js
