apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/routes/vault/cluster/access/leases/index.js index.js@third_party/openbao/ui/app/routes/vault/cluster/access/leases/index.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/leases/list-root.js
  list-root.js@third_party/openbao/ui/app/routes/vault/cluster/access/leases/list-root.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/leases/list.js list.js@third_party/openbao/ui/app/routes/vault/cluster/access/leases/list.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/leases/show.js show.js@third_party/openbao/ui/app/routes/vault/cluster/access/leases/show.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-routes-vault-cluster-access-leases
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
