apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/helpers/-date-base.js -date-base.js@third_party/openbao/ui/app/helpers/-date-base.js
- file:third_party/openbao/ui/app/helpers/add-to-array.js add-to-array.js@third_party/openbao/ui/app/helpers/add-to-array.js
- file:third_party/openbao/ui/app/helpers/add.js add.js@third_party/openbao/ui/app/helpers/add.js
- file:third_party/openbao/ui/app/helpers/await.js await.js@third_party/openbao/ui/app/helpers/await.js
- file:third_party/openbao/ui/app/helpers/aws-regions.js aws-regions.js@third_party/openbao/ui/app/helpers/aws-regions.js
- file:third_party/openbao/ui/app/helpers/coerce-eq.js coerce-eq.js@third_party/openbao/ui/app/helpers/coerce-eq.js
- file:third_party/openbao/ui/app/helpers/current-mount-path.js current-mount-path.js@third_party/openbao/ui/app/helpers/current-mount-path.js
- file:third_party/openbao/ui/app/helpers/date-from-now.js date-from-now.js@third_party/openbao/ui/app/helpers/date-from-now.js
- file:third_party/openbao/ui/app/helpers/filter-wildcard.js filter-wildcard.js@third_party/openbao/ui/app/helpers/filter-wildcard.js
- file:third_party/openbao/ui/app/helpers/has-permission.js has-permission.js@third_party/openbao/ui/app/helpers/has-permission.js
- file:third_party/openbao/ui/app/helpers/is-after.js is-after.js@third_party/openbao/ui/app/helpers/is-after.js
- file:third_party/openbao/ui/app/helpers/is-before.js is-before.js@third_party/openbao/ui/app/helpers/is-before.js
- file:third_party/openbao/ui/app/helpers/is-empty-value.js is-empty-value.js@third_party/openbao/ui/app/helpers/is-empty-value.js
- file:third_party/openbao/ui/app/helpers/is-wildcard-string.js is-wildcard-string.js@third_party/openbao/ui/app/helpers/is-wildcard-string.js
- file:third_party/openbao/ui/app/helpers/jsonify.js jsonify.js@third_party/openbao/ui/app/helpers/jsonify.js
- file:third_party/openbao/ui/app/helpers/mountable-auth-methods.js mountable-auth-methods.js@third_party/openbao/ui/app/helpers/mountable-auth-methods.js
- file:third_party/openbao/ui/app/helpers/mountable-secret-engines.js mountable-secret-engines.js@third_party/openbao/ui/app/helpers/mountable-secret-engines.js
- file:third_party/openbao/ui/app/helpers/multi-line-join.js multi-line-join.js@third_party/openbao/ui/app/helpers/multi-line-join.js
- file:third_party/openbao/ui/app/helpers/nav-to-route.js nav-to-route.js@third_party/openbao/ui/app/helpers/nav-to-route.js
- file:third_party/openbao/ui/app/helpers/now.js now.js@third_party/openbao/ui/app/helpers/now.js
- file:third_party/openbao/ui/app/helpers/number-to-word.js number-to-word.js@third_party/openbao/ui/app/helpers/number-to-word.js
- file:third_party/openbao/ui/app/helpers/remove-from-array.js remove-from-array.js@third_party/openbao/ui/app/helpers/remove-from-array.js
- file:third_party/openbao/ui/app/helpers/route-params-for.js route-params-for.js@third_party/openbao/ui/app/helpers/route-params-for.js
- file:third_party/openbao/ui/app/helpers/secret-query-params.js secret-query-params.js@third_party/openbao/ui/app/helpers/secret-query-params.js
- file:third_party/openbao/ui/app/helpers/sha2-digest-sizes.js sha2-digest-sizes.js@third_party/openbao/ui/app/helpers/sha2-digest-sizes.js
- file:third_party/openbao/ui/app/helpers/split-object.js split-object.js@third_party/openbao/ui/app/helpers/split-object.js
- file:third_party/openbao/ui/app/helpers/stringify.js stringify.js@third_party/openbao/ui/app/helpers/stringify.js
- file:third_party/openbao/ui/app/helpers/sub.js sub.js@third_party/openbao/ui/app/helpers/sub.js
- file:third_party/openbao/ui/app/helpers/supported-auth-backends.js supported-auth-backends.js@third_party/openbao/ui/app/helpers/supported-auth-backends.js
- file:third_party/openbao/ui/app/helpers/supported-managed-auth-backends.js supported-managed-auth-backends.js@third_party/openbao/ui/app/helpers/supported-managed-auth-backends.js
- file:third_party/openbao/ui/app/helpers/supported-secret-backends.js supported-secret-backends.js@third_party/openbao/ui/app/helpers/supported-secret-backends.js
- file:third_party/openbao/ui/app/helpers/tabs-for-auth-section.js tabs-for-auth-section.js@third_party/openbao/ui/app/helpers/tabs-for-auth-section.js
- file:third_party/openbao/ui/app/helpers/tabs-for-identity-show.js tabs-for-identity-show.js@third_party/openbao/ui/app/helpers/tabs-for-identity-show.js
- file:third_party/openbao/ui/app/helpers/to-label.js to-label.js@third_party/openbao/ui/app/helpers/to-label.js
- file:third_party/openbao/ui/app/helpers/tools-actions.js tools-actions.js@third_party/openbao/ui/app/helpers/tools-actions.js
- file:third_party/openbao/ui/app/helpers/wizard-constants.js wizard-constants.js@third_party/openbao/ui/app/helpers/wizard-constants.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-helpers
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
