apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/routes/vault/cluster/access/oidc/scopes/create.js
  create.js@third_party/openbao/ui/app/routes/vault/cluster/access/oidc/scopes/create.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/oidc/scopes/index.js
  index.js@third_party/openbao/ui/app/routes/vault/cluster/access/oidc/scopes/index.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/oidc/scopes/scope.js
  scope.js@third_party/openbao/ui/app/routes/vault/cluster/access/oidc/scopes/scope.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-routes-vault-cluster-access-oidc-scopes
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
