apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/kubernetes/addon/routes/roles/create.js create.js@third_party/openbao/ui/lib/kubernetes/addon/routes/roles/create.js
- file:third_party/openbao/ui/lib/kubernetes/addon/routes/roles/index.js index.js@third_party/openbao/ui/lib/kubernetes/addon/routes/roles/index.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-kubernetes-addon-routes-roles
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
