apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/routes/vault/cluster/access/identity/create.js create.js@third_party/openbao/ui/app/routes/vault/cluster/access/identity/create.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/identity/edit.js edit.js@third_party/openbao/ui/app/routes/vault/cluster/access/identity/edit.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/identity/index.js index.js@third_party/openbao/ui/app/routes/vault/cluster/access/identity/index.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/identity/merge.js merge.js@third_party/openbao/ui/app/routes/vault/cluster/access/identity/merge.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/identity/show.js show.js@third_party/openbao/ui/app/routes/vault/cluster/access/identity/show.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-routes-vault-cluster-access-identity
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
