apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/unit/decorators/model-expanded-attributes-test.js
  model-expanded-attributes-test.js@third_party/openbao/ui/tests/unit/decorators/model-expanded-attributes-test.js
- file:third_party/openbao/ui/tests/unit/decorators/model-form-fields-test.js model-form-fields-test.js@third_party/openbao/ui/tests/unit/decorators/model-form-fields-test.js
- file:third_party/openbao/ui/tests/unit/decorators/model-validations-test.js model-validations-test.js@third_party/openbao/ui/tests/unit/decorators/model-validations-test.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-unit-decorators
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
