apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/models/oidc/assignment.js assignment.js@third_party/openbao/ui/app/models/oidc/assignment.js
- file:third_party/openbao/ui/app/models/oidc/client.js client.js@third_party/openbao/ui/app/models/oidc/client.js
- file:third_party/openbao/ui/app/models/oidc/key.js key.js@third_party/openbao/ui/app/models/oidc/key.js
- file:third_party/openbao/ui/app/models/oidc/provider.js provider.js@third_party/openbao/ui/app/models/oidc/provider.js
- file:third_party/openbao/ui/app/models/oidc/scope.js scope.js@third_party/openbao/ui/app/models/oidc/scope.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-models-oidc
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
