apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/unit/models/capabilities-test.js capabilities-test.js@third_party/openbao/ui/tests/unit/models/capabilities-test.js
- file:third_party/openbao/ui/tests/unit/models/role-jwt-test.js role-jwt-test.js@third_party/openbao/ui/tests/unit/models/role-jwt-test.js
- file:third_party/openbao/ui/tests/unit/models/secret-engine-test.js secret-engine-test.js@third_party/openbao/ui/tests/unit/models/secret-engine-test.js
- file:third_party/openbao/ui/tests/unit/models/secret-v2-version-test.js secret-v2-version-test.js@third_party/openbao/ui/tests/unit/models/secret-v2-version-test.js
- file:third_party/openbao/ui/tests/unit/models/transit-key-test.js transit-key-test.js@third_party/openbao/ui/tests/unit/models/transit-key-test.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-unit-models
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
