apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js cross-sign.js@third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js
- file:third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/details.js details.js@third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/details.js
- file:third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/edit.js edit.js@third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/edit.js
- file:third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/rotate-root.js rotate-root.js@third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/rotate-root.js
- file:third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/sign.js sign.js@third_party/openbao/ui/lib/pki/addon/routes/issuers/issuer/sign.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-pki-addon-routes-issuers-issuer
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
