apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/forwarding/request_forwarding.go request_forwarding.go@third_party/openbao/internal/vault/forwarding/request_forwarding.go
- file:third_party/openbao/internal/vault/forwarding/request_forwarding_rpc.go request_forwarding_rpc.go@third_party/openbao/internal/vault/forwarding/request_forwarding_rpc.go
- file:third_party/openbao/internal/vault/forwarding/request_forwarding_service.pb.go
  request_forwarding_service.pb.go@third_party/openbao/internal/vault/forwarding/request_forwarding_service.pb.go
- file:third_party/openbao/internal/vault/forwarding/request_forwarding_service_grpc.pb.go
  request_forwarding_service_grpc.pb.go@third_party/openbao/internal/vault/forwarding/request_forwarding_service_grpc.pb.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-forwarding
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
