apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/external_tests/plugin/external_plugin_test.go
  external_plugin_test.go@third_party/openbao/internal/vault/external_tests/plugin/external_plugin_test.go
- file:third_party/openbao/internal/vault/external_tests/plugin/plugin_test.go plugin_test.go@third_party/openbao/internal/vault/external_tests/plugin/plugin_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-external-tests-plugin
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
