apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/pki/addon/routes/configuration/create.js create.js@third_party/openbao/ui/lib/pki/addon/routes/configuration/create.js
- file:third_party/openbao/ui/lib/pki/addon/routes/configuration/edit.js edit.js@third_party/openbao/ui/lib/pki/addon/routes/configuration/edit.js
- file:third_party/openbao/ui/lib/pki/addon/routes/configuration/index.js index.js@third_party/openbao/ui/lib/pki/addon/routes/configuration/index.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-pki-addon-routes-configuration
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
