apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/physical/cache.go cache.go@third_party/openbao/sdk/physical/cache.go
- file:third_party/openbao/sdk/physical/encoding.go encoding.go@third_party/openbao/sdk/physical/encoding.go
- file:third_party/openbao/sdk/physical/entry.go entry.go@third_party/openbao/sdk/physical/entry.go
- file:third_party/openbao/sdk/physical/error.go error.go@third_party/openbao/sdk/physical/error.go
- file:third_party/openbao/sdk/physical/latency.go latency.go@third_party/openbao/sdk/physical/latency.go
- file:third_party/openbao/sdk/physical/listing.go listing.go@third_party/openbao/sdk/physical/listing.go
- file:third_party/openbao/sdk/physical/physical.go physical.go@third_party/openbao/sdk/physical/physical.go
- file:third_party/openbao/sdk/physical/physical_access.go physical_access.go@third_party/openbao/sdk/physical/physical_access.go
- file:third_party/openbao/sdk/physical/physical_view.go physical_view.go@third_party/openbao/sdk/physical/physical_view.go
- file:third_party/openbao/sdk/physical/testing.go testing.go@third_party/openbao/sdk/physical/testing.go
- file:third_party/openbao/sdk/physical/transactions.go transactions.go@third_party/openbao/sdk/physical/transactions.go
- file:third_party/openbao/sdk/physical/write_notifier.go write_notifier.go@third_party/openbao/sdk/physical/write_notifier.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-physical
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
