apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/core/app/components/list-item/content.js content.js@third_party/openbao/ui/lib/core/app/components/list-item/content.js
- file:third_party/openbao/ui/lib/core/app/components/list-item/popup-menu.js popup-menu.js@third_party/openbao/ui/lib/core/app/components/list-item/popup-menu.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-core-app-components-list-item
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
