apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/core/addon/components/confirm/message.js message.js@third_party/openbao/ui/lib/core/addon/components/confirm/message.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-core-addon-components-confirm
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
