apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/database/dbplugin/v5/conversions_test.go conversions_test.go@third_party/openbao/sdk/database/dbplugin/v5/conversions_test.go
- file:third_party/openbao/sdk/database/dbplugin/v5/database.go database.go@third_party/openbao/sdk/database/dbplugin/v5/database.go
- file:third_party/openbao/sdk/database/dbplugin/v5/grpc_client.go grpc_client.go@third_party/openbao/sdk/database/dbplugin/v5/grpc_client.go
- file:third_party/openbao/sdk/database/dbplugin/v5/grpc_client_test.go grpc_client_test.go@third_party/openbao/sdk/database/dbplugin/v5/grpc_client_test.go
- file:third_party/openbao/sdk/database/dbplugin/v5/grpc_database_plugin.go grpc_database_plugin.go@third_party/openbao/sdk/database/dbplugin/v5/grpc_database_plugin.go
- file:third_party/openbao/sdk/database/dbplugin/v5/grpc_server.go grpc_server.go@third_party/openbao/sdk/database/dbplugin/v5/grpc_server.go
- file:third_party/openbao/sdk/database/dbplugin/v5/grpc_server_test.go grpc_server_test.go@third_party/openbao/sdk/database/dbplugin/v5/grpc_server_test.go
- file:third_party/openbao/sdk/database/dbplugin/v5/marshalling.go marshalling.go@third_party/openbao/sdk/database/dbplugin/v5/marshalling.go
- file:third_party/openbao/sdk/database/dbplugin/v5/middleware.go middleware.go@third_party/openbao/sdk/database/dbplugin/v5/middleware.go
- file:third_party/openbao/sdk/database/dbplugin/v5/middleware_test.go middleware_test.go@third_party/openbao/sdk/database/dbplugin/v5/middleware_test.go
- file:third_party/openbao/sdk/database/dbplugin/v5/plugin_client.go plugin_client.go@third_party/openbao/sdk/database/dbplugin/v5/plugin_client.go
- file:third_party/openbao/sdk/database/dbplugin/v5/plugin_client_test.go plugin_client_test.go@third_party/openbao/sdk/database/dbplugin/v5/plugin_client_test.go
- file:third_party/openbao/sdk/database/dbplugin/v5/plugin_factory.go plugin_factory.go@third_party/openbao/sdk/database/dbplugin/v5/plugin_factory.go
- file:third_party/openbao/sdk/database/dbplugin/v5/plugin_server.go plugin_server.go@third_party/openbao/sdk/database/dbplugin/v5/plugin_server.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-database-dbplugin-v5
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
