apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/scripts/codemods/dropdown-transform.js dropdown-transform.js@third_party/openbao/ui/scripts/codemods/dropdown-transform.js
- file:third_party/openbao/ui/scripts/codemods/icon-transform.js icon-transform.js@third_party/openbao/ui/scripts/codemods/icon-transform.js
- file:third_party/openbao/ui/scripts/codemods/inject-service.js inject-service.js@third_party/openbao/ui/scripts/codemods/inject-service.js
- file:third_party/openbao/ui/scripts/codemods/jscodeshift-babylon-parser.js jscodeshift-babylon-parser.js@third_party/openbao/ui/scripts/codemods/jscodeshift-babylon-parser.js
- file:third_party/openbao/ui/scripts/codemods/linkto-with-on-modifier.js linkto-with-on-modifier.js@third_party/openbao/ui/scripts/codemods/linkto-with-on-modifier.js
- file:third_party/openbao/ui/scripts/codemods/no-quoteless-attributes.js no-quoteless-attributes.js@third_party/openbao/ui/scripts/codemods/no-quoteless-attributes.js
- file:third_party/openbao/ui/scripts/codemods/transform-deprecated-args.js transform-deprecated-args.js@third_party/openbao/ui/scripts/codemods/transform-deprecated-args.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-scripts-codemods
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
