apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/builtin/logical/ssh/backend.go backend.go@third_party/openbao/internal/builtin/logical/ssh/backend.go
- file:third_party/openbao/internal/builtin/logical/ssh/backend_test.go backend_test.go@third_party/openbao/internal/builtin/logical/ssh/backend_test.go
- file:third_party/openbao/internal/builtin/logical/ssh/fields.go fields.go@third_party/openbao/internal/builtin/logical/ssh/fields.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_cleanup_dynamic_host_keys.go
  path_cleanup_dynamic_host_keys.go@third_party/openbao/internal/builtin/logical/ssh/path_cleanup_dynamic_host_keys.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_config_ca.go path_config_ca.go@third_party/openbao/internal/builtin/logical/ssh/path_config_ca.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_config_ca_test.go path_config_ca_test.go@third_party/openbao/internal/builtin/logical/ssh/path_config_ca_test.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_config_issuers.go path_config_issuers.go@third_party/openbao/internal/builtin/logical/ssh/path_config_issuers.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_config_issuers_test.go
  path_config_issuers_test.go@third_party/openbao/internal/builtin/logical/ssh/path_config_issuers_test.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_config_zeroaddress.go
  path_config_zeroaddress.go@third_party/openbao/internal/builtin/logical/ssh/path_config_zeroaddress.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_creds_create.go path_creds_create.go@third_party/openbao/internal/builtin/logical/ssh/path_creds_create.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_fetch.go path_fetch.go@third_party/openbao/internal/builtin/logical/ssh/path_fetch.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_issue.go path_issue.go@third_party/openbao/internal/builtin/logical/ssh/path_issue.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_issue_sign.go path_issue_sign.go@third_party/openbao/internal/builtin/logical/ssh/path_issue_sign.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_issuers.go path_issuers.go@third_party/openbao/internal/builtin/logical/ssh/path_issuers.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_lookup.go path_lookup.go@third_party/openbao/internal/builtin/logical/ssh/path_lookup.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_roles.go path_roles.go@third_party/openbao/internal/builtin/logical/ssh/path_roles.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_sign.go path_sign.go@third_party/openbao/internal/builtin/logical/ssh/path_sign.go
- file:third_party/openbao/internal/builtin/logical/ssh/path_verify.go path_verify.go@third_party/openbao/internal/builtin/logical/ssh/path_verify.go
- file:third_party/openbao/internal/builtin/logical/ssh/secret_otp.go secret_otp.go@third_party/openbao/internal/builtin/logical/ssh/secret_otp.go
- file:third_party/openbao/internal/builtin/logical/ssh/storage.go storage.go@third_party/openbao/internal/builtin/logical/ssh/storage.go
- file:third_party/openbao/internal/builtin/logical/ssh/storage_migrations.go storage_migrations.go@third_party/openbao/internal/builtin/logical/ssh/storage_migrations.go
- file:third_party/openbao/internal/builtin/logical/ssh/storage_migrations_test.go
  storage_migrations_test.go@third_party/openbao/internal/builtin/logical/ssh/storage_migrations_test.go
- file:third_party/openbao/internal/builtin/logical/ssh/util.go util.go@third_party/openbao/internal/builtin/logical/ssh/util.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-builtin-logical-ssh
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
