apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/integration/components/auth-config-form/options-test.js
  options-test.js@third_party/openbao/ui/tests/integration/components/auth-config-form/options-test.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-integration-components-auth-config-form
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
