apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/helper/roottoken/decode.go decode.go@third_party/openbao/sdk/helper/roottoken/decode.go
- file:third_party/openbao/sdk/helper/roottoken/encode.go encode.go@third_party/openbao/sdk/helper/roottoken/encode.go
- file:third_party/openbao/sdk/helper/roottoken/encode_test.go encode_test.go@third_party/openbao/sdk/helper/roottoken/encode_test.go
- file:third_party/openbao/sdk/helper/roottoken/otp.go otp.go@third_party/openbao/sdk/helper/roottoken/otp.go
- file:third_party/openbao/sdk/helper/roottoken/otp_test.go otp_test.go@third_party/openbao/sdk/helper/roottoken/otp_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-helper-roottoken
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
