apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/decorators/model-expanded-attributes.js model-expanded-attributes.js@third_party/openbao/ui/app/decorators/model-expanded-attributes.js
- file:third_party/openbao/ui/app/decorators/model-form-fields.js model-form-fields.js@third_party/openbao/ui/app/decorators/model-form-fields.js
- file:third_party/openbao/ui/app/decorators/model-validations.js model-validations.js@third_party/openbao/ui/app/decorators/model-validations.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-decorators
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
