apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/config/environment.d.ts environment.d.ts@third_party/openbao/ui/app/config/environment.d.ts
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-config
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
