apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/adapters/application.js application.js@third_party/openbao/ui/app/adapters/application.js
- file:third_party/openbao/ui/app/adapters/auth-method.js auth-method.js@third_party/openbao/ui/app/adapters/auth-method.js
- file:third_party/openbao/ui/app/adapters/aws-credential.js aws-credential.js@third_party/openbao/ui/app/adapters/aws-credential.js
- file:third_party/openbao/ui/app/adapters/capabilities.js capabilities.js@third_party/openbao/ui/app/adapters/capabilities.js
- file:third_party/openbao/ui/app/adapters/cluster.js cluster.js@third_party/openbao/ui/app/adapters/cluster.js
- file:third_party/openbao/ui/app/adapters/console.js console.js@third_party/openbao/ui/app/adapters/console.js
- file:third_party/openbao/ui/app/adapters/generated-item-list.js generated-item-list.js@third_party/openbao/ui/app/adapters/generated-item-list.js
- file:third_party/openbao/ui/app/adapters/lease.js lease.js@third_party/openbao/ui/app/adapters/lease.js
- file:third_party/openbao/ui/app/adapters/mfa-login-enforcement.js mfa-login-enforcement.js@third_party/openbao/ui/app/adapters/mfa-login-enforcement.js
- file:third_party/openbao/ui/app/adapters/mfa-method.js mfa-method.js@third_party/openbao/ui/app/adapters/mfa-method.js
- file:third_party/openbao/ui/app/adapters/mfa-setup.js mfa-setup.js@third_party/openbao/ui/app/adapters/mfa-setup.js
- file:third_party/openbao/ui/app/adapters/named-path.js named-path.js@third_party/openbao/ui/app/adapters/named-path.js
- file:third_party/openbao/ui/app/adapters/namespace.js namespace.js@third_party/openbao/ui/app/adapters/namespace.js
- file:third_party/openbao/ui/app/adapters/node.js node.js@third_party/openbao/ui/app/adapters/node.js
- file:third_party/openbao/ui/app/adapters/permissions.js permissions.js@third_party/openbao/ui/app/adapters/permissions.js
- file:third_party/openbao/ui/app/adapters/policy.js policy.js@third_party/openbao/ui/app/adapters/policy.js
- file:third_party/openbao/ui/app/adapters/raft-join.js raft-join.js@third_party/openbao/ui/app/adapters/raft-join.js
- file:third_party/openbao/ui/app/adapters/role-aws.js role-aws.js@third_party/openbao/ui/app/adapters/role-aws.js
- file:third_party/openbao/ui/app/adapters/role-jwt.js role-jwt.js@third_party/openbao/ui/app/adapters/role-jwt.js
- file:third_party/openbao/ui/app/adapters/role-ssh.js role-ssh.js@third_party/openbao/ui/app/adapters/role-ssh.js
- file:third_party/openbao/ui/app/adapters/secret-engine.js secret-engine.js@third_party/openbao/ui/app/adapters/secret-engine.js
- file:third_party/openbao/ui/app/adapters/secret-v2-version.js secret-v2-version.js@third_party/openbao/ui/app/adapters/secret-v2-version.js
- file:third_party/openbao/ui/app/adapters/secret-v2.js secret-v2.js@third_party/openbao/ui/app/adapters/secret-v2.js
- file:third_party/openbao/ui/app/adapters/secret.js secret.js@third_party/openbao/ui/app/adapters/secret.js
- file:third_party/openbao/ui/app/adapters/server.js server.js@third_party/openbao/ui/app/adapters/server.js
- file:third_party/openbao/ui/app/adapters/ssh-otp-credential.js ssh-otp-credential.js@third_party/openbao/ui/app/adapters/ssh-otp-credential.js
- file:third_party/openbao/ui/app/adapters/ssh-sign.js ssh-sign.js@third_party/openbao/ui/app/adapters/ssh-sign.js
- file:third_party/openbao/ui/app/adapters/ssh.js ssh.js@third_party/openbao/ui/app/adapters/ssh.js
- file:third_party/openbao/ui/app/adapters/tools.js tools.js@third_party/openbao/ui/app/adapters/tools.js
- file:third_party/openbao/ui/app/adapters/transit-key.js transit-key.js@third_party/openbao/ui/app/adapters/transit-key.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-adapters
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
