apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
  create-and-edit.js@third_party/openbao/ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
- file:third_party/openbao/ui/lib/kubernetes/addon/components/page/role/details.js
  details.js@third_party/openbao/ui/lib/kubernetes/addon/components/page/role/details.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-kubernetes-addon-components-page-role
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
