apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/builtin/logical/kubernetes/cmd/kubernetes/main.go
  main.go@third_party/openbao/internal/builtin/logical/kubernetes/cmd/kubernetes/main.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-builtin-logical-kubernetes-cmd-kubernetes
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
