apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/plugin/pb/backend.pb.go backend.pb.go@third_party/openbao/sdk/plugin/pb/backend.pb.go
- file:third_party/openbao/sdk/plugin/pb/backend_grpc.pb.go backend_grpc.pb.go@third_party/openbao/sdk/plugin/pb/backend_grpc.pb.go
- file:third_party/openbao/sdk/plugin/pb/translation.go translation.go@third_party/openbao/sdk/plugin/pb/translation.go
- file:third_party/openbao/sdk/plugin/pb/translation_test.go translation_test.go@third_party/openbao/sdk/plugin/pb/translation_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-plugin-pb
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
