apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/builtin/logical/kubernetes/integrationtest/kind/config.yaml
  config.yaml@third_party/openbao/internal/builtin/logical/kubernetes/integrationtest/kind/config.yaml
kind: SystemContext
metadata:
  name: third-party-openbao-internal-builtin-logical-kubernetes-integrationtest-kind
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
