apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/models/kubernetes/config.js config.js@third_party/openbao/ui/app/models/kubernetes/config.js
- file:third_party/openbao/ui/app/models/kubernetes/role.js role.js@third_party/openbao/ui/app/models/kubernetes/role.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-models-kubernetes
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
