apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/controllers/vault/cluster/access/mfa/methods/create.js
  create.js@third_party/openbao/ui/app/controllers/vault/cluster/access/mfa/methods/create.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-controllers-vault-cluster-access-mfa-methods
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
