apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/website/src/docusaurus-plugin-sidebar-json/index.ts index.ts@third_party/openbao/website/src/docusaurus-plugin-sidebar-json/index.ts
kind: SystemContext
metadata:
  name: third-party-openbao-website-src-docusaurus-plugin-sidebar-json
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
