apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-certificate-details.ts
  pki-certificate-details.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-certificate-details.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-configuration-details.ts
  pki-configuration-details.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-configuration-details.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-configuration-edit.ts
  pki-configuration-edit.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-configuration-edit.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-configure-create.ts
  pki-configure-create.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-configure-create.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-details.ts
  pki-issuer-details.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-details.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-edit.ts pki-issuer-edit.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-edit.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-generate-intermediate.ts
  pki-issuer-generate-intermediate.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-generate-intermediate.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-generate-root.ts
  pki-issuer-generate-root.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-generate-root.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-import.ts pki-issuer-import.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-import.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-rotate-root.ts
  pki-issuer-rotate-root.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-issuer-rotate-root.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-key-details.ts pki-key-details.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-key-details.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-overview.ts pki-overview.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-overview.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-role-details.ts pki-role-details.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-role-details.ts
- file:third_party/openbao/ui/lib/pki/addon/components/page/pki-tidy-status.ts pki-tidy-status.ts@third_party/openbao/ui/lib/pki/addon/components/page/pki-tidy-status.ts
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-pki-addon-components-page
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
