apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/core/app/helpers/changelog-url-for.js changelog-url-for.js@third_party/openbao/ui/lib/core/app/helpers/changelog-url-for.js
- file:third_party/openbao/ui/lib/core/app/helpers/cluster-states.js cluster-states.js@third_party/openbao/ui/lib/core/app/helpers/cluster-states.js
- file:third_party/openbao/ui/lib/core/app/helpers/date-format.js date-format.js@third_party/openbao/ui/lib/core/app/helpers/date-format.js
- file:third_party/openbao/ui/lib/core/app/helpers/format-duration.js format-duration.js@third_party/openbao/ui/lib/core/app/helpers/format-duration.js
- file:third_party/openbao/ui/lib/core/app/helpers/format-number.js format-number.js@third_party/openbao/ui/lib/core/app/helpers/format-number.js
- file:third_party/openbao/ui/lib/core/app/helpers/img-path.js img-path.js@third_party/openbao/ui/lib/core/app/helpers/img-path.js
- file:third_party/openbao/ui/lib/core/app/helpers/is-active-route.js is-active-route.js@third_party/openbao/ui/lib/core/app/helpers/is-active-route.js
- file:third_party/openbao/ui/lib/core/app/helpers/loose-equal.js loose-equal.js@third_party/openbao/ui/lib/core/app/helpers/loose-equal.js
- file:third_party/openbao/ui/lib/core/app/helpers/message-types.js message-types.js@third_party/openbao/ui/lib/core/app/helpers/message-types.js
- file:third_party/openbao/ui/lib/core/app/helpers/options-for-backend.js options-for-backend.js@third_party/openbao/ui/lib/core/app/helpers/options-for-backend.js
- file:third_party/openbao/ui/lib/core/app/helpers/path-or-array.js path-or-array.js@third_party/openbao/ui/lib/core/app/helpers/path-or-array.js
- file:third_party/openbao/ui/lib/core/app/helpers/sanitized-html.js sanitized-html.js@third_party/openbao/ui/lib/core/app/helpers/sanitized-html.js
- file:third_party/openbao/ui/lib/core/app/helpers/set-flash-message.js set-flash-message.js@third_party/openbao/ui/lib/core/app/helpers/set-flash-message.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-core-app-helpers
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
