apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/helper/ldaputil/client.go client.go@third_party/openbao/sdk/helper/ldaputil/client.go
- file:third_party/openbao/sdk/helper/ldaputil/client_test.go client_test.go@third_party/openbao/sdk/helper/ldaputil/client_test.go
- file:third_party/openbao/sdk/helper/ldaputil/config.go config.go@third_party/openbao/sdk/helper/ldaputil/config.go
- file:third_party/openbao/sdk/helper/ldaputil/config_test.go config_test.go@third_party/openbao/sdk/helper/ldaputil/config_test.go
- file:third_party/openbao/sdk/helper/ldaputil/connection.go connection.go@third_party/openbao/sdk/helper/ldaputil/connection.go
- file:third_party/openbao/sdk/helper/ldaputil/ldap.go ldap.go@third_party/openbao/sdk/helper/ldaputil/ldap.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-helper-ldaputil
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
