apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-pages-secrets-backend-kv
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/pages/secrets/backend/kv/edit-secret.js edit-secret.js@third_party/openbao/ui/tests/pages/secrets/backend/kv/edit-secret.js
- file:third_party/openbao/ui/tests/pages/secrets/backend/kv/show.js show.js@third_party/openbao/ui/tests/pages/secrets/backend/kv/show.js
