apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/website/src/components/HomepageFeatures/index.tsx index.tsx@third_party/openbao/website/src/components/HomepageFeatures/index.tsx
kind: SystemContext
metadata:
  name: third-party-openbao-website-src-components-homepagefeatures
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
