apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-helpers-pki
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/helpers/pki/overview.js overview.js@third_party/openbao/ui/tests/helpers/pki/overview.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-configure-create.js pki-configure-create.js@third_party/openbao/ui/tests/helpers/pki/pki-configure-create.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-delete-all-issuers.js pki-delete-all-issuers.js@third_party/openbao/ui/tests/helpers/pki/pki-delete-all-issuers.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-generate-root.js pki-generate-root.js@third_party/openbao/ui/tests/helpers/pki/pki-generate-root.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-issuer-cross-sign.js pki-issuer-cross-sign.js@third_party/openbao/ui/tests/helpers/pki/pki-issuer-cross-sign.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-issuer-details.js pki-issuer-details.js@third_party/openbao/ui/tests/helpers/pki/pki-issuer-details.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-key-form.js pki-key-form.js@third_party/openbao/ui/tests/helpers/pki/pki-key-form.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-not-valid-after-form.js pki-not-valid-after-form.js@third_party/openbao/ui/tests/helpers/pki/pki-not-valid-after-form.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-role-form.js pki-role-form.js@third_party/openbao/ui/tests/helpers/pki/pki-role-form.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-role-generate.js pki-role-generate.js@third_party/openbao/ui/tests/helpers/pki/pki-role-generate.js
- file:third_party/openbao/ui/tests/helpers/pki/pki-run-commands.js pki-run-commands.js@third_party/openbao/ui/tests/helpers/pki/pki-run-commands.js
- file:third_party/openbao/ui/tests/helpers/pki/values.js values.js@third_party/openbao/ui/tests/helpers/pki/values.js
- file:third_party/openbao/ui/tests/helpers/pki/workflow.js workflow.js@third_party/openbao/ui/tests/helpers/pki/workflow.js
