apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/models/pki/action.js action.js@third_party/openbao/ui/app/models/pki/action.js
- file:third_party/openbao/ui/app/models/pki/issuer.js issuer.js@third_party/openbao/ui/app/models/pki/issuer.js
- file:third_party/openbao/ui/app/models/pki/key.js key.js@third_party/openbao/ui/app/models/pki/key.js
- file:third_party/openbao/ui/app/models/pki/role.js role.js@third_party/openbao/ui/app/models/pki/role.js
- file:third_party/openbao/ui/app/models/pki/sign-intermediate.js sign-intermediate.js@third_party/openbao/ui/app/models/pki/sign-intermediate.js
- file:third_party/openbao/ui/app/models/pki/tidy.js tidy.js@third_party/openbao/ui/app/models/pki/tidy.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-models-pki
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
