apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-integration-components-oidc
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/integration/components/oidc/assignment-form-test.js
  assignment-form-test.js@third_party/openbao/ui/tests/integration/components/oidc/assignment-form-test.js
- file:third_party/openbao/ui/tests/integration/components/oidc/client-form-test.js
  client-form-test.js@third_party/openbao/ui/tests/integration/components/oidc/client-form-test.js
- file:third_party/openbao/ui/tests/integration/components/oidc/key-form-test.js key-form-test.js@third_party/openbao/ui/tests/integration/components/oidc/key-form-test.js
- file:third_party/openbao/ui/tests/integration/components/oidc/provider-form-test.js
  provider-form-test.js@third_party/openbao/ui/tests/integration/components/oidc/provider-form-test.js
- file:third_party/openbao/ui/tests/integration/components/oidc/scope-form-test.js
  scope-form-test.js@third_party/openbao/ui/tests/integration/components/oidc/scope-form-test.js
