apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/serviceregistration/kubernetes/client/client.go
  client.go@third_party/openbao/internal/serviceregistration/kubernetes/client/client.go
- file:third_party/openbao/internal/serviceregistration/kubernetes/client/client_test.go
  client_test.go@third_party/openbao/internal/serviceregistration/kubernetes/client/client_test.go
- file:third_party/openbao/internal/serviceregistration/kubernetes/client/config.go
  config.go@third_party/openbao/internal/serviceregistration/kubernetes/client/config.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-serviceregistration-kubernetes-client
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
