apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-types-ember-cli-flash-services
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
