apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/helper/ocsp/client.go client.go@third_party/openbao/sdk/helper/ocsp/client.go
- file:third_party/openbao/sdk/helper/ocsp/ocsp_test.go ocsp_test.go@third_party/openbao/sdk/helper/ocsp/ocsp_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-helper-ocsp
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
