apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/external_tests/namespaces/namespace_test.go
  namespace_test.go@third_party/openbao/internal/vault/external_tests/namespaces/namespace_test.go
- file:third_party/openbao/internal/vault/external_tests/namespaces/sealing_test.go
  sealing_test.go@third_party/openbao/internal/vault/external_tests/namespaces/sealing_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-external-tests-namespaces
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
