apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/models/database/connection.js connection.js@third_party/openbao/ui/app/models/database/connection.js
- file:third_party/openbao/ui/app/models/database/credential.js credential.js@third_party/openbao/ui/app/models/database/credential.js
- file:third_party/openbao/ui/app/models/database/role.js role.js@third_party/openbao/ui/app/models/database/role.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-models-database
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
