apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/helpers/components/sidebar-nav.js sidebar-nav.js@third_party/openbao/ui/tests/helpers/components/sidebar-nav.js
- file:third_party/openbao/ui/tests/helpers/components/ttl-picker.js ttl-picker.js@third_party/openbao/ui/tests/helpers/components/ttl-picker.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-helpers-components
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
