apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/lib/kubernetes/addon/components/page/configure.js configure.js@third_party/openbao/ui/lib/kubernetes/addon/components/page/configure.js
- file:third_party/openbao/ui/lib/kubernetes/addon/components/page/credentials.js
  credentials.js@third_party/openbao/ui/lib/kubernetes/addon/components/page/credentials.js
- file:third_party/openbao/ui/lib/kubernetes/addon/components/page/overview.js overview.js@third_party/openbao/ui/lib/kubernetes/addon/components/page/overview.js
- file:third_party/openbao/ui/lib/kubernetes/addon/components/page/roles.js roles.js@third_party/openbao/ui/lib/kubernetes/addon/components/page/roles.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-lib-kubernetes-addon-components-page
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
