apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-integration-components-kubernetes-page-role
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
codeRefIndex:
- file:third_party/openbao/ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
  create-and-edit-test.js@third_party/openbao/ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
- file:third_party/openbao/ui/tests/integration/components/kubernetes/page/role/details-test.js
  details-test.js@third_party/openbao/ui/tests/integration/components/kubernetes/page/role/details-test.js
