apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/routes/vault/cluster-base.js cluster-base.js@third_party/openbao/ui/app/routes/vault/cluster-base.js
- file:third_party/openbao/ui/app/routes/vault/cluster.js cluster.js@third_party/openbao/ui/app/routes/vault/cluster.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-routes-vault
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
