apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/physical/pebbledb/pebbledb.go pebbledb.go@third_party/openbao/internal/physical/pebbledb/pebbledb.go
- file:third_party/openbao/internal/physical/pebbledb/pebbledb_test.go pebbledb_test.go@third_party/openbao/internal/physical/pebbledb/pebbledb_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-physical-pebbledb
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
