apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/controllers/vault/cluster/access/oidc/clients/client.js
  client.js@third_party/openbao/ui/app/controllers/vault/cluster/access/oidc/clients/client.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-controllers-vault-cluster-access-oidc-clients
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
