apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/helper/benchhelpers/benchhelpers.go benchhelpers.go@third_party/openbao/internal/helper/benchhelpers/benchhelpers.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-helper-benchhelpers
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
