apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/helper/flag-slice/flag.go flag.go@third_party/openbao/internal/helper/flag-slice/flag.go
- file:third_party/openbao/internal/helper/flag-slice/flag_test.go flag_test.go@third_party/openbao/internal/helper/flag-slice/flag_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-helper-flag-slice
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
