apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/external_tests/api/api_integration_test.go
  api_integration_test.go@third_party/openbao/internal/vault/external_tests/api/api_integration_test.go
- file:third_party/openbao/internal/vault/external_tests/api/index_test.go index_test.go@third_party/openbao/internal/vault/external_tests/api/index_test.go
- file:third_party/openbao/internal/vault/external_tests/api/kv_helpers_test.go kv_helpers_test.go@third_party/openbao/internal/vault/external_tests/api/kv_helpers_test.go
- file:third_party/openbao/internal/vault/external_tests/api/renewer_integration_test.go
  renewer_integration_test.go@third_party/openbao/internal/vault/external_tests/api/renewer_integration_test.go
- file:third_party/openbao/internal/vault/external_tests/api/secret_test.go secret_test.go@third_party/openbao/internal/vault/external_tests/api/secret_test.go
- file:third_party/openbao/internal/vault/external_tests/api/sudo_paths_test.go sudo_paths_test.go@third_party/openbao/internal/vault/external_tests/api/sudo_paths_test.go
- file:third_party/openbao/internal/vault/external_tests/api/sys_rotate_ext_test.go
  sys_rotate_ext_test.go@third_party/openbao/internal/vault/external_tests/api/sys_rotate_ext_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-external-tests-api
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
