apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/queue/priority_queue.go priority_queue.go@third_party/openbao/sdk/queue/priority_queue.go
- file:third_party/openbao/sdk/queue/priority_queue_test.go priority_queue_test.go@third_party/openbao/sdk/queue/priority_queue_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-queue
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
