apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-database-dbplugin-v5-testing
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
