apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/helper/versions/version.go version.go@third_party/openbao/internal/helper/versions/version.go
- file:third_party/openbao/internal/helper/versions/version_test.go version_test.go@third_party/openbao/internal/helper/versions/version_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-helper-versions
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
