apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
  parsed-certificate-info-rows-test.js@third_party/openbao/ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-generate-csr-test.js
  pki-generate-csr-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-generate-csr-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-generate-root-test.js
  pki-generate-root-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-generate-root-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-generate-toggle-groups-test.js
  pki-generate-toggle-groups-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-generate-toggle-groups-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
  pki-import-pem-bundle-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
  pki-issuer-cross-sign-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-issuer-details-test.js
  pki-issuer-details-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-issuer-details-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-key-form-test.js
  pki-key-form-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-key-form-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-key-parameters-test.js
  pki-key-parameters-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-key-parameters-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-key-usage-test.js
  pki-key-usage-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-key-usage-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-not-valid-after-form-test.js
  pki-not-valid-after-form-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-not-valid-after-form-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-role-form-test.js
  pki-role-form-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-role-form-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-role-generate-test.js
  pki-role-generate-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-role-generate-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
  pki-sign-intermediate-form-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
- file:third_party/openbao/ui/tests/integration/components/pki/pki-tidy-form-test.js
  pki-tidy-form-test.js@third_party/openbao/ui/tests/integration/components/pki/pki-tidy-form-test.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-integration-components-pki
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
