apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/builtin/logical/rabbitmq/backend.go backend.go@third_party/openbao/internal/builtin/logical/rabbitmq/backend.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/backend_test.go backend_test.go@third_party/openbao/internal/builtin/logical/rabbitmq/backend_test.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/passwords.go passwords.go@third_party/openbao/internal/builtin/logical/rabbitmq/passwords.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_config_connection.go
  path_config_connection.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_config_connection.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_config_connection_test.go
  path_config_connection_test.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_config_connection_test.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_config_lease.go
  path_config_lease.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_config_lease.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_config_lease_test.go
  path_config_lease_test.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_config_lease_test.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_role_create.go path_role_create.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_role_create.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_role_create_test.go
  path_role_create_test.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_role_create_test.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/path_roles.go path_roles.go@third_party/openbao/internal/builtin/logical/rabbitmq/path_roles.go
- file:third_party/openbao/internal/builtin/logical/rabbitmq/secret_creds.go secret_creds.go@third_party/openbao/internal/builtin/logical/rabbitmq/secret_creds.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-builtin-logical-rabbitmq
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
