apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/external_tests/identity/aliases_test.go
  aliases_test.go@third_party/openbao/internal/vault/external_tests/identity/aliases_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/cross_namespace_test.go
  cross_namespace_test.go@third_party/openbao/internal/vault/external_tests/identity/cross_namespace_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/entities_test.go
  entities_test.go@third_party/openbao/internal/vault/external_tests/identity/entities_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/group_aliases_test.go
  group_aliases_test.go@third_party/openbao/internal/vault/external_tests/identity/group_aliases_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/groups_test.go groups_test.go@third_party/openbao/internal/vault/external_tests/identity/groups_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/identity_test.go
  identity_test.go@third_party/openbao/internal/vault/external_tests/identity/identity_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/login_mfa_duo_test.go
  login_mfa_duo_test.go@third_party/openbao/internal/vault/external_tests/identity/login_mfa_duo_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/login_mfa_totp_test.go
  login_mfa_totp_test.go@third_party/openbao/internal/vault/external_tests/identity/login_mfa_totp_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/oidc_provider_test.go
  oidc_provider_test.go@third_party/openbao/internal/vault/external_tests/identity/oidc_provider_test.go
- file:third_party/openbao/internal/vault/external_tests/identity/userlockouts_test.go
  userlockouts_test.go@third_party/openbao/internal/vault/external_tests/identity/userlockouts_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-external-tests-identity
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
