apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/command/agent/exec/exec.go exec.go@third_party/openbao/internal/command/agent/exec/exec.go
- file:third_party/openbao/internal/command/agent/exec/exec_test.go exec_test.go@third_party/openbao/internal/command/agent/exec/exec_test.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-command-agent-exec
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
