apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/initializers/deprecation-filter.js deprecation-filter.js@third_party/openbao/ui/app/initializers/deprecation-filter.js
- file:third_party/openbao/ui/app/initializers/disable-ember-inspector.js disable-ember-inspector.js@third_party/openbao/ui/app/initializers/disable-ember-inspector.js
- file:third_party/openbao/ui/app/initializers/ember-data-identifiers.js ember-data-identifiers.js@third_party/openbao/ui/app/initializers/ember-data-identifiers.js
- file:third_party/openbao/ui/app/initializers/enable-engines.js enable-engines.js@third_party/openbao/ui/app/initializers/enable-engines.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-initializers
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
