apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/serializers/keymgmt/key.js key.js@third_party/openbao/ui/app/serializers/keymgmt/key.js
- file:third_party/openbao/ui/app/serializers/keymgmt/provider.js provider.js@third_party/openbao/ui/app/serializers/keymgmt/provider.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-serializers-keymgmt
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
