apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/tests/helpers/pki/page/pki-configuration-edit.js pki-configuration-edit.js@third_party/openbao/ui/tests/helpers/pki/page/pki-configuration-edit.js
- file:third_party/openbao/ui/tests/helpers/pki/page/pki-keys.js pki-keys.js@third_party/openbao/ui/tests/helpers/pki/page/pki-keys.js
- file:third_party/openbao/ui/tests/helpers/pki/page/pki-role-details.js pki-role-details.js@third_party/openbao/ui/tests/helpers/pki/page/pki-role-details.js
- file:third_party/openbao/ui/tests/helpers/pki/page/pki-tidy-form.js pki-tidy-form.js@third_party/openbao/ui/tests/helpers/pki/page/pki-tidy-form.js
- file:third_party/openbao/ui/tests/helpers/pki/page/pki-tidy.js pki-tidy.js@third_party/openbao/ui/tests/helpers/pki/page/pki-tidy.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-tests-helpers-pki-page
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
