apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/sdk/helper/dbtxn/dbtxn.go dbtxn.go@third_party/openbao/sdk/helper/dbtxn/dbtxn.go
kind: SystemContext
metadata:
  name: third-party-openbao-sdk-helper-dbtxn
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
