apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/vault/cluster/cluster.go cluster.go@third_party/openbao/internal/vault/cluster/cluster.go
- file:third_party/openbao/internal/vault/cluster/inmem_layer.go inmem_layer.go@third_party/openbao/internal/vault/cluster/inmem_layer.go
- file:third_party/openbao/internal/vault/cluster/inmem_layer_test.go inmem_layer_test.go@third_party/openbao/internal/vault/cluster/inmem_layer_test.go
- file:third_party/openbao/internal/vault/cluster/simulations.go simulations.go@third_party/openbao/internal/vault/cluster/simulations.go
- file:third_party/openbao/internal/vault/cluster/tcp_layer.go tcp_layer.go@third_party/openbao/internal/vault/cluster/tcp_layer.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-vault-cluster
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
