apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/helper/storagepacker/storagepacker.go storagepacker.go@third_party/openbao/internal/helper/storagepacker/storagepacker.go
- file:third_party/openbao/internal/helper/storagepacker/storagepacker_test.go storagepacker_test.go@third_party/openbao/internal/helper/storagepacker/storagepacker_test.go
- file:third_party/openbao/internal/helper/storagepacker/types.pb.go types.pb.go@third_party/openbao/internal/helper/storagepacker/types.pb.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-helper-storagepacker
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
