apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/internal/helper/identity/mfa/mfa.go mfa.go@third_party/openbao/internal/helper/identity/mfa/mfa.go
- file:third_party/openbao/internal/helper/identity/mfa/sentinel.go sentinel.go@third_party/openbao/internal/helper/identity/mfa/sentinel.go
- file:third_party/openbao/internal/helper/identity/mfa/types.pb.go types.pb.go@third_party/openbao/internal/helper/identity/mfa/types.pb.go
kind: SystemContext
metadata:
  name: third-party-openbao-internal-helper-identity-mfa
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
