apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:third_party/openbao/ui/app/routes/vault/cluster/access/oidc/providers/create.js
  create.js@third_party/openbao/ui/app/routes/vault/cluster/access/oidc/providers/create.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/oidc/providers/index.js
  index.js@third_party/openbao/ui/app/routes/vault/cluster/access/oidc/providers/index.js
- file:third_party/openbao/ui/app/routes/vault/cluster/access/oidc/providers/provider.js
  provider.js@third_party/openbao/ui/app/routes/vault/cluster/access/oidc/providers/provider.js
kind: SystemContext
metadata:
  name: third-party-openbao-ui-app-routes-vault-cluster-access-oidc-providers
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
