apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: tools-open-architecture
  namespace: default
spec:
  repository: deno-kcp
  upstream: self
  dependsOn:
  - sc.deno-kcp
codeRefIndex:
- file:.tools/open-architecture/arch.yaml arch.yaml@.tools/open-architecture/arch.yaml
- file:.tools/open-architecture/validate.py validate.py@.tools/open-architecture/validate.py
